services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
