services:
  web: 
    environment:
      - NODE_ENV=production
    ports:
      - 3002:80
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Maximum 50% of a single CPU core
          memory: 512M        # Maximum RAM allowed
        reservations:
          cpus: '0.25'        # Guaranteed CPU amount
          memory: 128M
    build:
      context: .
      dockerfile: dockerfile
  # caddy:
  #   image: caddy:2.7-alpine
  #   restart: unless-stopped 
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
